#!/bin/bash

take=$(sed -n '/#--/,/#--/{/#--PUBLIC ACCESS--#/!{/#--/!{/^#/!{/./p}}}}' /etc/apache2/sites-enabled/rcsis.ir.conf | grep "Use publish" | grep -v "www" | awk '{print $4}')
AvailableDirectory="/etc/apache2/sites-available/"
SiteDirectory="/etc/apache2/sites-available/public/public.conf"

file=$SiteDirectory

CmdSub(){
domain=$1
echo "Intext Echo"
for SUBDOMAIN in ${take[@]}
do
        DOMAIN=$SUBDOMAIN.$domain
        echo "take ssl for $DOMAIN"
	certbot certonly --webroot --webroot-path /var/www/html --config-dir /etc/apache2/ssl/ -d $DOMAIN --agree-tos --manual-public-ip-logging-ok --cert-path /etc/apache2/ssl/archive/$DOMAIN/cert.pem --cert-name $DOMAIN
done
}


CmdRoot() {
DOMAIN=$1
certbot certonly --webroot --webroot-path /var/www/html --config-dir /etc/apache2/ssl/ -d $DOMAIN -d www.$DOMAIN --agree-tos --manual-public-ip-logging-ok --cert-path /etc/apache2/ssl/archive/$DOMAIN/cert.pem --cert-name $DOMAIN
}


MakeSsl(){
if [ -x "$(command -v certbot)" ]; then
	echo "certbot is already installed." 
	#echo $@
	cat << 'EOF' > $AvailableDirectory/ssl.conf
<Location "/.well-known">
        ProxyPass "!"
        SecRuleEngine off
</Location>
Alias /.well-known /var/www/html/.well-known
<Directory "/var/www/html/.well-known">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
</Directory>
EOF
pattern="IncludeOptional /etc/apache2/sites-available/ssl.conf"
replacement="#IncludeOptional /etc/apache2/sites-available/ssl.conf"

# Check if the pattern exists in the file
if ! grep -q "$replacement" "$file"; then
    echo "$replacement" >> "$file"
fi
if  grep -q "$replacement" "$file"; then
	pattern="IncludeOptional \/etc\/apache2\/sites-available\/ssl.conf"
	replacement="#IncludeOptional \/etc\/apache2\/sites-available\/ssl.conf"
    	sed -i "s/$replacement/$pattern/g" "$file"
fi
service apache2 restart
	$1 $3

sed -i "s/$pattern/$replacement/g" "$file"
service apache2 restart
	

else
	echo "certbot is NOT installed." 
	sudo apt-get install python3 python3-venv libaugeas0
	sudo python3 -m venv /opt/certbot/
	sudo /opt/certbot/bin/pip install --upgrade pip
	sudo /opt/certbot/bin/pip install certbot certbot-apache
	sudo ln -s /opt/certbot/bin/certbot /usr/bin/certbot

fi
}
if [ -n "$1" ]; then
    case "$1" in
        -r|r)
		MakeSsl CmdRoot $@
                ;;
        -s|s)
                MakeSsl CmdSub $@
                ;;
        -h|h)
                echo """
r for root domain
s for sub domain
                """
                ;;
        *)
		echo "input switches or for help <iecw -h>"
            ;;
    esac
else
    echo "input switches or for help <iecw -h>"
fi
                        

