services:
  dispatcher:
    image: ecwi:latest
    volumes:
      - ./data/conf:/etc/apache2
      - ./data/logs:/var/log/apache2
      - ./data/www:/var/www
    ports:
      - "80:80"
      - "443:443"
    user: root
